spring.application.name=attendance-service
server.port=${SERVER_PORT:8081}
server.forward-headers-strategy=framework
spring.main.allow-bean-definition-overriding=true

# DATABASE
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/attendance_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres123}
spring.datasource.driver-class-name=org.postgresql.Driver

# ??? dev ????? update, ????? ????? "relation ... does not exist"
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}

spring.jpa.open-in-view=false
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.jpa.defer-datasource-initialization=true

# OPENAPI (????? ??? GATEWAY)
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false

# JWT
security.jwt.secret=${SECURITY_JWT_SECRET:+i38C96CqmxwIheqUXRKPHpO/07bWCgLE2SnYJgOQl4=}
security.jwt.expiration-ms=${SECURITY_JWT_EXPIRATION_MS:900000}

# USER-SERVICE CLIENT
services.user-service.base-url=${USER_SERVICE_BASE_URL:http://user-service:8080}

# ACTUATOR
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
