spring.application.name=gateway
server.port=8080
server.forward-headers-strategy=framework

app.user-base-url=${USER_SERVICE_BASE_URL:http://user-service:8080}
app.att-base-url=${ATTENDANCE_SERVICE_BASE_URL:http://attendance-service:8081}

spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=${app.user-base-url}
spring.cloud.gateway.routes[0].predicates[0]=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[0].filters[1]=AddRequestHeader=X-Forwarded-Prefix,/user

spring.cloud.gateway.routes[1].id=attendance-service
spring.cloud.gateway.routes[1].uri=${app.att-base-url}
spring.cloud.gateway.routes[1].predicates[0]=Path=/attendance/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1
spring.cloud.gateway.routes[1].filters[1]=AddRequestHeader=X-Forwarded-Prefix,/attendance

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.disable-swagger-default-url=true

springdoc.swagger-ui.urls[0].name=user-service
springdoc.swagger-ui.urls[0].url=/user/v3/api-docs

springdoc.swagger-ui.urls[1].name=attendance-service
springdoc.swagger-ui.urls[1].url=/attendance/v3/api-docs

management.endpoints.web.exposure.include=health,info,gateway
management.endpoint.health.show-details=always
