services:
  postgres:
    image: postgres:16
    container_name: attendance-postgres
    environment:
      POSTGRES_DB: attendance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d attendance_db"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: attendance-redis
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    restart: unless-stopped

  user-service:
    build:
      context: .
      dockerfile: user-service/Dockerfile
    container_name: user-service
    environment:
      SERVER_PORT: 8080
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendance_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SECURITY_JWT_SECRET: +i38C96CqmxwIheqUXRKPHpO/07bWCgLE2SnYJgOQl4=

      # чтобы таблицы создавались (иначе будет "relation users does not exist")
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8082:8080"
    restart: unless-stopped

  attendance-service:
    build:
      context: .
      dockerfile: attendance-service/Dockerfile
    container_name: attendance-service
    environment:
      SERVER_PORT: 8081
      SPRING_PROFILES_ACTIVE: dev

      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/attendance_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123

      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379

      SECURITY_JWT_SECRET: +i38C96CqmxwIheqUXRKPHpO/07bWCgLE2SnYJgOQl4=

      # ✅ ВАЖНО: переменная должна совпадать с твоим application.properties
      USER_SERVICE_BASE_URL: http://user-service:8080
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      user-service:
        condition: service_started
    ports:
      - "8083:8081"
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: gateway/Dockerfile
    container_name: gateway
    environment:
      SERVER_PORT: 8080
      USER_SERVICE_BASE_URL: http://user-service:8080
      ATTENDANCE_SERVICE_BASE_URL: http://attendance-service:8081
    depends_on:
      user-service:
        condition: service_started
      attendance-service:
        condition: service_started
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  pgdata:
  redisdata:
