spring.application.name=user-service
server.port=${SERVER_PORT:8080}

server.forward-headers-strategy=framework
spring.main.allow-bean-definition-overriding=true

# =========================
# PROFILES / ENV
# =========================
spring.profiles.active=${SPRING_PROFILES_ACTIVE:dev}


app.superadmin.username=${APP_SUPERADMIN_USERNAME:superadmin}
app.superadmin.email=${APP_SUPERADMIN_EMAIL:superadmin@mail.com}
app.superadmin.password=${APP_SUPERADMIN_PASSWORD:SuperAdmin123}


spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/attendance_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres123}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=${SPRING_JPA_DDL_AUTO:update}

spring.jpa.open-in-view=false
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.sql.init.mode=${SPRING_SQL_INIT_MODE:never}
spring.jpa.defer-datasource-initialization=true


spring.data.redis.host=${SPRING_REDIS_HOST:redis}
spring.data.redis.port=${SPRING_REDIS_PORT:6379}
spring.data.redis.timeout=5s

spring.data.redis.lettuce.pool.enabled=true
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=1
spring.data.redis.lettuce.pool.max-wait=5s

security.jwt.secret=${SECURITY_JWT_SECRET:+i38C96CqmxwIheqUXRKPHpO/07bWCgLE2SnYJgOQl4=}
security.jwt.expiration-ms=${SECURITY_JWT_EXPIRATION_MS:900000}
security.jwt.refresh-expiration-ms=${SECURITY_JWT_REFRESH_EXPIRATION_MS:604800000}
security.jwt.blacklist-ttl-ms=${SECURITY_JWT_BLACKLIST_TTL_MS:${SECURITY_JWT_EXPIRATION_MS:900000}}


management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always


logging.level.root=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.jdbc.core.JdbcTemplate=DEBUG
logging.level.org.springframework.data.redis=INFO
# logging.level.org.springframework.security=DEBUG

server.error.include-message=always
server.error.include-stacktrace=always
